%% SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
%% Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
%% ═══════════════════════════════════════════════════════════════════════════
%% cuda_oxide_emitter.pl — generate Rust/CUDA-oxide kernels from Prolog facts.
%%
%% THE RESEARCH PROGRAM: kernels are GENERATED from declarative facts, across
%% multiple backends (C++/CUDA, Rust/cuda-oxide, LLVM IR, MLIR, PyTorch graphs).
%% This is the Rust/cuda-oxide backend emitter. It reads unary-elementwise op
%% facts (robust_op_match-style) and emits a complete cuda-oxide example crate:
%% the #[kernel] device fn + host launch + bit-identity self-check.
%%
%% The fact's per-element semantics (the FORMULATION + pinned FP coordinates)
%% are the single source of truth — the same fact drives every backend, so all
%% backends are bit-identical-by-construction projections of one spec.
%%
%% Usage:  emit_oxide_unary(+OpFact, +OutFile)
%%   where OpFact = oxide_op(Name, RustExpr, RefExpr, EdgeNote)
%%     Name     — kernel name (atom), e.g. relu, silu
%%     RustExpr — Rust per-element body over `v` (the device expression)
%%     RefExpr  — Rust CPU-reference expr over `v` (usually identical to RustExpr)
%%     EdgeNote — doc string of the bit-identity contract
%%
%% Author: Iyun, 2026-06-06 (cuda-oxide backend of the multi-backend generator)
%% ═══════════════════════════════════════════════════════════════════════════

:- module(cuda_oxide_emitter, [emit_oxide_unary/2, oxide_op/1, emit_oxide_binary/2, oxide_binop/1]).

%% ── op facts: the per-element Rust expression for each unary elementwise op ──
%% RustExpr/RefExpr are over `v: f32`. These mirror robust_op_match formulations,
%% translated to the Rust/cuda-oxide backend's expression.
%%   relu : 'x >= 0 ? x : 0.0f'        -> if v >= 0.0 { v } else { 0.0 }
%%   silu : x/(1+exp(-x)) divide-form  -> v / (1.0 + (-v).exp())   (exp = libdevice __nv_expf)
%%   sigmoid : 1/(1+exp(-x))           -> 1.0 / (1.0 + (-v).exp())
oxide_op(oxide_op(relu,
    "if v >= 0.0 { v } else { 0.0 }",
    "if v >= 0.0 { v } else { 0.0 }",
    "torch.relu: x>=0 ? x : 0. neg-zero stable (+0.0 for -0.0), NaN->0 (NaN>=0 false).")).
oxide_op(oxide_op(silu,
    "v / (1.0 + (-v).exp())",
    "v / (1.0 + (-v).exp())",
    "torch.silu = x*sigmoid(x) = x/(1+exp(-x)). DIVIDE form (NOT recip-mul, differs 1 ULP). exp via libdevice __nv_expf (cmath patch).")).
oxide_op(oxide_op(sigmoid,
    "1.0 / (1.0 + (-v).exp())",
    "1.0 / (1.0 + (-v).exp())",
    "torch.sigmoid = 1/(1+exp(-x)). exp via libdevice __nv_expf.")).

%% ── the emitter: generate a complete cuda-oxide example from an op fact ──
emit_oxide_unary(oxide_op(Name, RustExpr, RefExpr, EdgeNote), OutFile) :-
    open(OutFile, write, S),
    format(S, '/* GENERATED by cuda_oxide_emitter.pl from the ~w op fact.~n', [Name]),
    format(S, ' * Clean-room unary-elementwise kernel: c[i] = f(x[i]).~n', []),
    format(S, ' * Contract: ~w~n', [EdgeNote]),
    format(S, ' * Compiled Rust->PTX(sm_61) by cuda-oxide, run on the P4. No hand-writing.~n', []),
    format(S, ' */~n', []),
    format(S, 'use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};~n', []),
    format(S, 'use cuda_device::{DisjointSlice, cuda_module, kernel, thread};~n~n', []),
    %% the device kernel — the ONE varying line is the formulation
    format(S, '#[cuda_module]~n', []),
    format(S, 'mod kernels {~n    use super::*;~n', []),
    format(S, '    #[kernel]~n', []),
    format(S, '    pub fn ~w(x: &[f32], mut c: DisjointSlice<f32>) {~n', [Name]),
    format(S, '        let idx = thread::index_1d();~n', []),
    format(S, '        let idx_raw = idx.get();~n', []),
    format(S, '        if let Some(c_elem) = c.get_mut(idx) {~n', []),
    format(S, '            let v = x[idx_raw];~n', []),
    format(S, '            *c_elem = ~w;~n', [RustExpr]),
    format(S, '        }~n    }~n}~n~n', []),
    %% CPU reference — same expression
    format(S, 'fn ~w_ref(v: f32) -> f32 { ~w }~n~n', [Name, RefExpr]),
    %% host + bit-identity self-check (generated)
    emit_oxide_host(S, Name),
    close(S),
    format("Generated cuda-oxide ~w kernel -> ~w~n", [Name, OutFile]).

emit_oxide_host(S, Name) :-
    format(S, 'fn main() {~n', []),
    format(S, '    println!("=== GENERATED cuda-oxide ~w on Tesla P4 ===\\n");~n', [Name]),
    format(S, '    let ctx = CudaContext::new(0).expect("ctx");~n', []),
    format(S, '    let stream = ctx.default_stream();~n', []),
    %% edge-case + range test set (same as the hand-written oracle)
    format(S, '    let mut x_host: Vec<f32> = vec![0.0, -0.0, f32::NAN, -1.0, 1.0,~n', []),
    format(S, '        f32::MIN_POSITIVE, -f32::MIN_POSITIVE, 3.4e38, -3.4e38];~n', []),
    format(S, '    for i in 0..1015 { let t=(i as f32)*0.013-6.6; x_host.push(t*(if i%3==0 {-1.0} else {1.0})); }~n', []),
    format(S, '    let n = x_host.len();~n', []),
    format(S, '    let x_dev = DeviceBuffer::from_host(&stream, &x_host).unwrap();~n', []),
    format(S, '    let mut c_dev = DeviceBuffer::<f32>::zeroed(&stream, n).unwrap();~n', []),
    format(S, '    let module = kernels::load(&ctx).expect("load");~n', []),
    format(S, '    module.~w(&stream, LaunchConfig::for_num_elems(n as u32), &x_dev, &mut c_dev).expect("launch");~n', [Name]),
    format(S, '    let c_host = c_dev.to_host_vec(&stream).unwrap();~n', []),
    %% bitwise comparison vs the generated reference
    format(S, '    let mut diffs = 0usize; let mut first = None;~n', []),
    format(S, '    for i in 0..n {~n', []),
    format(S, '        let want = ~w_ref(x_host[i]); let got = c_host[i];~n', [Name]),
    format(S, '        let eq = want.to_bits()==got.to_bits() || (want.is_nan() && got.is_nan());~n', []),
    format(S, '        if !eq { if first.is_none() { first=Some((i,x_host[i],want,got)); } diffs+=1; }~n', []),
    format(S, '    }~n', []),
    format(S, '    if diffs==0 { println!("  *** 0 differences — BIT-IDENTICAL ({} elems) ***", n); }~n', []),
    format(S, '    else { let (i,xi,w,g)=first.unwrap();~n', []),
    format(S, '        println!("  {} differ. first idx {} x={} want={:#010x} got={:#010x}", diffs,i,xi,w.to_bits(),g.to_bits());~n', []),
    format(S, '        std::process::exit(1); }~n', []),
    format(S, '}~n', []).

%% ── binary elementwise: c[i] = op(a[i], b[i]) ──
oxide_binop(oxide_binop(add, "av + bv", "av + bv",
    "vecadd: c = a + b. exact f32 add, 0-ULP vs any reference.")).
oxide_binop(oxide_binop(mul, "av * bv", "av * bv",
    "elementwise mul: c = a * b. exact f32 mul.")).

emit_oxide_binary(oxide_binop(Name, RustExpr, RefExpr, EdgeNote), OutFile) :-
    open(OutFile, write, S),
    format(S, "/* GENERATED by cuda_oxide_emitter.pl from the ~w binop fact. */~n", [Name]),
    format(S, "/* Contract: ~w */~n", [EdgeNote]),
    format(S, "use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};~n", []),
    format(S, "use cuda_device::{DisjointSlice, cuda_module, kernel, thread};~n~n", []),
    format(S, "#[cuda_module]~nmod kernels {~n    use super::*;~n", []),
    format(S, "    #[kernel]~n", []),
    format(S, "    pub fn ~w(a: &[f32], b: &[f32], mut c: DisjointSlice<f32>) {~n", [Name]),
    format(S, "        let idx = thread::index_1d();~n        let i = idx.get();~n", []),
    format(S, "        if let Some(ce) = c.get_mut(idx) {~n", []),
    format(S, "            let av = a[i]; let bv = b[i];~n", []),
    format(S, "            *ce = ~w;~n        }~n    }~n}~n~n", [RustExpr]),
    format(S, "fn ~w_ref(av: f32, bv: f32) -> f32 { ~w }~n~n", [Name, RefExpr]),
    format(S, "fn main() {~n", []),
    format(S, "    println!(\"=== GENERATED cuda-oxide ~w (binary) on Tesla P4 ===\\n\");~n", [Name]),
    format(S, "    let ctx = CudaContext::new(0).expect(\"ctx\");~n    let stream = ctx.default_stream();~n", []),
    format(S, "    let n = 1024usize;~n", []),
    format(S, "    let a: Vec<f32> = (0..n).map(|i| i as f32 - 512.0).collect();~n", []),
    format(S, "    let b: Vec<f32> = (0..n).map(|i| (i as f32)*0.5 - 100.0).collect();~n", []),
    format(S, "    let ad = DeviceBuffer::from_host(&stream,&a).unwrap();~n", []),
    format(S, "    let bd = DeviceBuffer::from_host(&stream,&b).unwrap();~n", []),
    format(S, "    let mut cd = DeviceBuffer::<f32>::zeroed(&stream,n).unwrap();~n", []),
    format(S, "    let m = kernels::load(&ctx).expect(\"load\");~n", []),
    format(S, "    m.~w(&stream, LaunchConfig::for_num_elems(n as u32), &ad,&bd,&mut cd).expect(\"launch\");~n", [Name]),
    format(S, "    let ch = cd.to_host_vec(&stream).unwrap();~n", []),
    format(S, "    let mut diffs=0; for i in 0..n {~n", []),
    format(S, "        let want=~w_ref(a[i],b[i]);~n", [Name]),
    format(S, "        if want.to_bits()!=ch[i].to_bits() && !(want.is_nan()&&ch[i].is_nan()) { diffs+=1; }~n", []),
    format(S, "    }~n", []),
    format(S, "    if diffs==0 { println!(\"  *** 0 differences — BIT-IDENTICAL ({} elems) ***\", n); }~n", []),
    format(S, "    else { println!(\"  {} differ\", diffs); std::process::exit(1); }~n", []),
    format(S, "}~n", []),
    close(S),
    format("Generated cuda-oxide ~w binop -> ~w~n", [Name, OutFile]).
