%% SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
%% Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
%% robust_match_status.pl — Table(10100): Robust 0-ULP match status
%%
%% Per Heath's direction (2026-05-31): sibling to Table(10001). Same Stanford
%% L1/L2/L3 emission patterns x reference implementations grid, but tracks
%% Iyun's expanded methodology: not just "0 ULP on canonical input" but
%% robust 0-ULP — passes a range of input sizes AND numerical-edge-case
%% stability (e.g., -0.0 round-trips correctly, NaN/Inf propagate per IEEE,
%% denormals handled, etc.).
%%
%% Tier definition (Iyun's adapter classification):
%%   GOLD    — 0 ULP across the standard size sweep AND all edge-case checks
%%   SILVER  — 0 ULP on canonical size but not all robustness checks
%%   BRONZE  — within 4 ULP across the sweep
%%   UNTESTED — robustness harness has not yet measured this cell
%%
%% Substrate-architecture mirrors llvm_match_status.pl (Table 10001):
%%   - Prolog facts declare the substrate-of-record (robust_op_match/5)
%%   - SVG projection derives from facts via swipl -g main
%%   - Auto-generated by CI harness; no agent input claims tiers directly
%%   - Bookspine per cell, one bar per op, color = tier
%%   - Watermarkup: cell(table(10100),column(Ref),row(Pattern))
%%
%% Generated facts live at bpd/lib/robust_op_match.o.pl, populated by
%% bpd/tests/verify_robust_ops_auto.py (the robustness harness that wraps
%% Iyun's /tmp/iyun_ir_submit_adapter.py and sweeps sizes + edge cases).
%%
%% Reuses dashboard_common.pl (Iyun + mavchin's DRY substrate) for the
%% freshness stamp so this dashboard is provably-live on its face.

:- module(robust_match_status, [
    main/0,
    emission_pattern/3,
    reference_implementation/2,
    cells_in_pattern/2,
    op_in_pattern/2,
    tier_for/4,
    tier_color/2
]).

:- use_module(library(lists)).
:- use_module(lib/dashboard_common, [freshness_stamp_svg/4]).

%% ─── Table metadata ────────────────────────────────────────────────────

table_id(10100).
table_title('Robust 0-ULP match status').
table_subtitle('Stanford L1/L2/L3 kernels · 0 ULP + size sweep + edge-case stability').


%% ─── Rows: emission patterns (SAME 9 as Table 10001) ─────────────────
%%
%% Mirroring 10001 exactly. Future divergence (if Iyun adds patterns) lands
%% in BOTH tables since they share the same Stanford L1/L2/L3 corpus.

emission_pattern(unary_elementwise,         'unary elementwise',          12).
emission_pattern(binary_elementwise,        'binary elementwise',          1).
emission_pattern(reduction,                 'reduction',                   7).
emission_pattern(reduction_then_elementwise,'reduction + elementwise',     6).
emission_pattern(scan,                      'scan',                        2).
emission_pattern(conv_im2col,               'conv via im2col',             6).
emission_pattern(pool_reduce,               'pool / reduce',               3).
emission_pattern(loss_reduce,               'loss / reduce',               6).
emission_pattern(flash_attention,           'flash attention',             1).


%% ─── Columns: reference implementations (SAME 6 as Table 10001) ──────

reference_implementation(ggml_sse3,    'ggml SSE3').
reference_implementation(ggml_avx2,    'ggml AVX2').
reference_implementation(ggml_avx512,  'ggml AVX512').
reference_implementation(ggml_neon,    'ggml NEON').
reference_implementation(pytorch_mkl,  'PyTorch MKL').
reference_implementation(pytorch_nnpack,'PyTorch NNPACK').


%% ─── Tier → color mapping ────────────────────────────────────────────
%%
%% Per Iyun's adapter tier scheme. Colors chosen to be:
%%   - Distinct from Table 10001 (so the two dashboards read differently
%%     at a glance — robustness has its own visual identity)
%%   - Ordered (gold > silver > bronze > untested) so degraded tiers are
%%     visually subordinate

tier_color(gold,     '#d4af37').   %% deep gold — 0 ULP everywhere + all edge cases
tier_color(silver,   '#a8a8a8').   %% silver — 0 ULP canonical, missing some robustness
tier_color(bronze,   '#cd7f32').   %% bronze — within 4 ULP across sweep
tier_color(untested, '#3a3a3a').   %% dim — robustness harness not yet run


%% ─── Cell collection ─────────────────────────────────────────────────
%%
%% cells_in_pattern(+Pattern, -CellList): for each (Op, Ref) in this pattern,
%% emit a cell-record with its tier. Mirrors collect_op_spines/3 in 10001.

cells_in_pattern(Pattern, Cells) :-
    findall(cell(Op, Ref, Tier),
        ( op_in_pattern(Pattern, Op),
          reference_implementation(Ref, _),
          tier_for(Pattern, Op, Ref, Tier)
        ),
        Cells).

%% op_in_pattern is provided by robust_op_match facts (when loaded).
%% Without facts, no ops appear and the dashboard shows all-untested.
op_in_pattern(Pattern, Op) :-
    catch(robust_op_match(Pattern, Op, _, _, _), _, fail).

%% tier_for: explicit fact lookup, else untested
tier_for(Pattern, Op, Ref, Tier) :-
    ( catch(robust_op_match(Pattern, Op, Ref, T, _), _, fail)
    -> Tier = T
    ;  Tier = untested
    ).


%% ─── SVG emission ────────────────────────────────────────────────────

%% Layout constants chosen to mirror 10001's visual rhythm:
%%   - Header band 80px
%%   - Row label column 240px (left)
%%   - Cell column 160px each, 9 patterns × 32px spine height
%%   - Footer 40px with freshness stamp

dim(header_h, 80).
dim(row_label_w, 240).
dim(col_w, 160).
dim(spine_h, 6).
dim(spine_gap, 2).
dim(spine_margin_x, 8).
dim(spine_margin_y, 8).
dim(footer_h, 40).

row_height(P, H) :-
    emission_pattern(P, _, N),
    dim(spine_h, SH), dim(spine_gap, SG), dim(spine_margin_y, SMY),
    H is N * (SH + SG) + 2 * SMY.

total_height(H) :-
    findall(RH, (emission_pattern(P, _, _), row_height(P, RH)), RHs),
    sum_list(RHs, RowsH),
    dim(header_h, HH), dim(footer_h, FH),
    H is HH + RowsH + FH.

total_width(W) :-
    findall(_, reference_implementation(_, _), Refs),
    length(Refs, NRefs),
    dim(row_label_w, RLW), dim(col_w, CW),
    W is RLW + NRefs * CW.


%% Diviner contract: when run as `swipl -g main robust_match_status.pl -- <OutPath>`,
%% write the SVG to <OutPath>. Falls back to stdout for local development
%% (mirrors llvm_match_status.pl's pattern).
main :-
    current_prolog_flag(argv, Argv),
    ( Argv = [OutPath|_]
    -> setup_call_cleanup(
           open(OutPath, write, Stream),
           with_output_to(Stream, emit_svg),
           close(Stream)
         )
    ;  emit_svg
    ),
    halt(0).

%% emit_svg writes to current_output, so it composes both with stdout
%% (local dev: swipl -g main robust_match_status.pl) and with a file
%% stream (diviner: with_output_to(file(...), emit_svg)).
emit_svg :-
    consult_facts_if_present,
    total_width(W),
    total_height(H),
    format('<?xml version="1.0" encoding="UTF-8"?>~n', []),
    format('<svg xmlns="http://www.w3.org/2000/svg" width="~w" height="~w" viewBox="0 0 ~w ~w" font-family="Source Code Pro, monospace">~n',
           [W, H, W, H]),
    %% Background
    format('  <rect x="0" y="0" width="~w" height="~w" fill="#1a1a1a"/>~n', [W, H]),
    emit_header(W),
    emit_column_headers(W),
    emit_rows,
    emit_footer(W, H),
    format('</svg>~n', []).


emit_header(W) :-
    Mid is W // 2,
    table_id(TID), table_title(Title), table_subtitle(Subtitle),
    format('  <text x="~w" y="32" font-size="22" font-weight="bold" fill="#d4af37" text-anchor="middle">Table(~w) · ~w</text>~n',
           [Mid, TID, Title]),
    format('  <text x="~w" y="56" font-size="12" fill="#a8a8a8" text-anchor="middle">~w</text>~n',
           [Mid, Subtitle]).


emit_column_headers(_W) :-
    dim(row_label_w, RLW), dim(col_w, CW), dim(header_h, HH),
    HYBase is HH - 8,
    findall(R-N, reference_implementation(R, N), Refs),
    forall_with_idx(Refs, [I, _R-N]>>(
        X is RLW + I * CW + CW // 2,
        format('  <text x="~w" y="~w" font-size="11" fill="#a8a8a8" text-anchor="middle">~w</text>~n',
               [X, HYBase, N])
    )).


emit_rows :-
    dim(header_h, HH),
    findall(P-N-Ops, emission_pattern(P, N, Ops), Patterns),
    emit_rows_(Patterns, HH).

emit_rows_([], _).
emit_rows_([P-Name-_NOps | Rest], Y) :-
    row_height(P, RH),
    emit_row(P, Name, Y, RH),
    Y2 is Y + RH,
    emit_rows_(Rest, Y2).


emit_row(P, Name, Y, _RH) :-
    dim(row_label_w, RLW),
    dim(spine_margin_x, SMX), dim(spine_margin_y, SMY),
    dim(spine_h, SH), dim(spine_gap, SG), dim(col_w, CW),
    %% Row label
    LabelY is Y + 16,
    format('  <text x="8" y="~w" font-size="12" fill="#d4af37">~w</text>~n',
           [LabelY, Name]),
    %% Collect cells for this pattern
    cells_in_pattern(P, Cells),
    %% Unique ops in this pattern
    findall(Op, member(cell(Op, _, _), Cells), Ops0),
    sort(Ops0, Ops),
    %% For each (Op, Ref), draw bookspine bar
    findall(_, (
        nth0(OpIdx, Ops, Op),
        reference_implementation(Ref, _),
        nth0(RefIdx, [ggml_sse3, ggml_avx2, ggml_avx512, ggml_neon, pytorch_mkl, pytorch_nnpack], Ref),
        ( member(cell(Op, Ref, Tier), Cells) -> true ; Tier = untested ),
        tier_color(Tier, Color),
        X is RLW + RefIdx * CW + SMX,
        BarW is CW - 2 * SMX,
        BarY is Y + SMY + OpIdx * (SH + SG),
        cell_dim_expression(10100, Ref, P, DimExpr),
        format('  <rect data-dim="~w" data-op="~w" data-tier="~w" x="~w" y="~w" width="~w" height="~w" fill="~w" stroke="#0a0a0a" stroke-width="0.5">~n',
               [DimExpr, Op, Tier, X, BarY, BarW, SH, Color]),
        format('    <title>~w · ~w · ~w</title>~n', [P, Op, Tier]),
        format('  </rect>~n', [])
    ), _).


emit_footer(W, H) :-
    dim(footer_h, FH),
    FY is H - FH + 16,
    freshness_stamp_svg(current_output, 8, FY, 10),
    Mid is W // 2,
    FY2 is H - 8,
    format('  <text x="~w" y="~w" font-size="9" fill="#5a5a5a" text-anchor="middle">cell coords: cell(table(10100),column(Ref),row(Pattern)) · facts: bpd/lib/robust_op_match.o.pl · harness: bpd/tests/verify_robust_ops_auto.py</text>~n',
           [Mid, FY2]).


cell_dim_expression(Table, Column, Row, DimExpr) :-
    format(atom(DimExpr),
        'cell(table(~w),column(~w),row(~w))',
        [Table, Column, Row]).


%% ─── Helpers ─────────────────────────────────────────────────────────

forall_with_idx(List, Goal) :- forall_with_idx_(List, 0, Goal).
forall_with_idx_([], _, _).
forall_with_idx_([X|Xs], I, Goal) :-
    call(Goal, I, X),
    I1 is I + 1,
    forall_with_idx_(Xs, I1, Goal).


%% ─── Facts loading (with safe-silent-fallback) ──────────────────────
%%
%% The harness writes facts to bpd/lib/robust_op_match.o.pl. If absent,
%% all cells render UNTESTED — which is the correct visual state until
%% the harness runs. Matches 10001's discipline.

consult_facts_if_present :-
    %% Prefer the auto-generated .o.pl (written by the
    %% wire_referees_to_dashboard.py pipeline). Falls back to the schema-
    %% source seeds in .pl, then to no facts (all-untested rendering).
    %% Matches the 10001 convention: '.o' files are generated; without
    %% '.o', it's the schema-source.
    ( catch(use_module('lib/robust_op_match.o'), _, fail)
    -> true
    ; catch(use_module('bpd/lib/robust_op_match.o'), _, fail)
    -> true
    ; catch(use_module('lib/robust_op_match'), _, fail)
    -> true
    ; catch(use_module('bpd/lib/robust_op_match'), _, fail)
    -> true
    ; true
    ).

%% Invoked via: swipl -g main bpd/robust_match_status.pl
%% (Matches Table 10001 convention — no :- initialization directive,
%% so consult'ing this file doesn't auto-run main.)
