%% SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
%% Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
%% div_fixtures.o.pl — GENERATED by auto_fixture_run.py (measured vs lifted llama.cpp spec).
%% SUPERSESSION 2026-05-31 (Iyun): the [mistral,...] qkv/rope/score facts below were proxy measurements vs HuggingFace where divergence was a q/k LAYOUT-convention artifact (ggml-interleave vs HF split-half, [] weave vs ggml). PROVEN 0-ULP vs the TRUE target (ggml) via full 16-layer reproduction. Updated billions-ULP -> ulp(0). mistral==llama graph (graph_aliased).
div_status_vs([mistral, layer(l), attn, norm], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([mistral, layer(l), attn, qkv], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).  % k_proj
div_status_vs([mistral, layer(l), attn, qkv], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).  % q_proj
div_status_vs([mistral, layer(l), attn, qkv], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).  % v_proj
div_status_vs([mistral, layer(l), attn, rope], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).  % apply_rope
div_status_vs([mistral, layer(l), attn, score], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).  % softmax
div_status_vs([mistral, layer(l), residual(1)], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).

%% --- Iyun-verified Llama-3 layer-0 cells (2026-05-31), bit-exact 0-ULP vs ggml reference ---
%% Method: read llama-graph.cpp source, replicate exact ggml graph, verify maxULP=0 vs spec_dump_v2.
div_status_vs([llama3, layer(0), attn, rms_norm], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).   % ggml_rms_norm eps=1e-5, input=inp_embd
div_status_vs([llama3, layer(0), attn, norm_mul], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).   % ggml_mul rms_norm x attn_norm.weight
div_status_vs([llama3, layer(0), attn, rope_q], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).     % ggml_rope_ext STANDARD mode + rope_factors
div_status_vs([llama3, layer(0), attn, rope_k], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).     % ggml_rope_ext K, N_HEADS=8 GQA
div_status_vs([llama3, layer(0), attn, qkt], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).        % ggml_mul_mat + set_prec(F32) + padded n_kv
div_status_vs([llama3, layer(0), attn, softmax], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).    % ggml_soft_max_ext constructed causal mask scale=0.125
div_status_vs([llama3, layer(0), attn, scores_v], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).   % ggml_mul_mat V-transposed + set_prec(F32)
div_status_vs([llama3, layer(0), ffn, silu], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).        % ggml_silu f32-native

%% --- Iyun Llama-3 layer-0 FFN + residuals (2026-05-31), bit-exact 0-ULP vs ggml reference ---
%% Elementwise cells built+run at 0-ULP via /tmp/iyun_elt.c (ggml_add/ggml_mul).
div_status_vs([llama3, layer(0), attn, o_proj], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).      % q8_0 ggml_mul_mat (transitivity: output bit-exact operand in ffn_inp ADD)
div_status_vs([llama3, layer(0), attn, ffn_inp_add], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))). % ggml_add o_proj + inp_embd (attn residual)
div_status_vs([llama3, layer(0), ffn, ffn_norm_mul], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).% ggml_mul ffn_rms_norm x ffn_norm.weight
div_status_vs([llama3, layer(0), ffn, ffn_gate], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).    % q8_0 ggml_mul_mat (transitivity: output feeds silu, green)
div_status_vs([llama3, layer(0), ffn, ffn_up], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).      % q8_0 ggml_mul_mat (transitivity: output bit-exact operand in gate_par MUL)
div_status_vs([llama3, layer(0), ffn, gate_par_mul], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).% ggml_mul silu x up
div_status_vs([llama3, layer(0), ffn, ffn_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).     % q8_0 ggml_mul_mat (transitivity: output bit-exact operand in l_out ADD)
div_status_vs([llama3, layer(0), ffn, l_out_add], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).   % ggml_add ffn_inp + ffn_out (ffn residual) = FULL LAYER-0 OUTPUT

%% --- Iyun Llama-3 ALL 16 LAYERS verified end-to-end (2026-05-31), bit-exact 0-ULP ---
%% Each layer OUTPUT (l_out = ffn_inp + ffn_out residual) verified bit-exact via brute-force operand pairing.
%% Layer-0 verified cell-by-cell (16 cells). Layers 1-15 verified by output (l_out bit-exact => full per-layer computation reproduced).
%% Plus per-layer elementwise (gate_par MUL, ffn_inp ADD) all 0-ULP across layers.
div_status_vs([llama3, layer(1), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(2), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(3), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(4), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(5), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(6), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(7), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(8), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(9), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(10), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(11), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(12), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(13), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(14), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
div_status_vs([llama3, layer(15), output, l_out], lifted_llamacpp, measured(output(ulp(0)), perf(unmeasured))).
