%% SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
%% Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
%% ═══════════════════════════════════════════════════════════════════════════
%% prolog_to_llvm.pl — Emit LLVM IR from BPD Prolog facts
%%
%% Phase 1: k_add (elementwise addition)
%%
%% Usage:
%%   swipl -g "emit_kernel(k_add, 'bpd_add.ll'), halt" prolog_to_llvm.pl
%%
%% Author: medayek (Collective SME, Verification Methodology)
%% Licensed under GPLv2
%% ═══════════════════════════════════════════════════════════════════════════

:- module(prolog_to_llvm, [
    emit_kernel/2,
    emit_kernel/3,
    emit_q8_0_dot/1,
    emit_q8_0_dot_vec/1,
    emit_q8_0_dot_intrin/1,
    emit_q8_0_dot/2
]).

:- use_module(library(lists)).

%% ═══════════════════════════════════════════════════════════════
%% BPD kernel facts (the WHAT)
%% ═══════════════════════════════════════════════════════════════

%! kernel_op(+Name, +Type, +Inputs, +Outputs)
kernel_op(k_add, elementwise, [a, b], [x]).
kernel_op(k_mul, elementwise, [a, b], [x]).
kernel_op(k_sub, elementwise, [a, b], [x]).
kernel_op(k_relu, elementwise, [a], [x]).
kernel_op(k_neg, elementwise, [a], [x]).
kernel_op(k_abs, elementwise, [a], [x]).

%! elementwise_llvm_op(+Name, -LLVMOp)
elementwise_llvm_op(k_add, "fadd").
elementwise_llvm_op(k_mul, "fmul").
elementwise_llvm_op(k_sub, "fsub").

%% ═══════════════════════════════════════════════════════════════
%% Target parameters (the HOW — sweepable)
%% ═══════════════════════════════════════════════════════════════

:- dynamic target_param/2.

% Defaults (Ivy Bridge, no FMA, SSE4.1)
default_target(vector_width, 4).       % <4 x float> for SSE
default_target(has_fma, false).
default_target(alignment, 16).         % SSE alignment
default_target(triple, "x86_64-unknown-linux-gnu").
default_target(features, "+sse4.1").

get_target(Param, Value) :-
    target_param(Param, Value), !.
get_target(Param, Value) :-
    default_target(Param, Value).

%% ═══════════════════════════════════════════════════════════════
%% LLVM IR emission — scalar path
%% ═══════════════════════════════════════════════════════════════

%! emit_kernel(+Name, +OutputFile) is det.
%  Emit LLVM IR for a kernel to a file.
emit_kernel(Name, OutputFile) :-
    emit_kernel(Name, OutputFile, scalar).

%! emit_kernel(+Name, +OutputFile, +Mode) is det.
%  Mode: scalar | vectorized
emit_kernel(Name, OutputFile, Mode) :-
    open(OutputFile, write, S),
    emit_header(S, Name),
    (Mode == vectorized ->
        emit_vectorized_body(S, Name)
    ;
        emit_scalar_body(S, Name)
    ),
    emit_footer(S),
    close(S),
    format("Emitted ~w to ~w (~w mode)~n", [Name, OutputFile, Mode]).

%% Header: target triple, datalayout, function declaration
emit_header(S, Name) :-
    get_target(triple, Triple),
    kernel_op(Name, elementwise, Inputs, _),
    length(Inputs, NInputs),
    % Function name
    kernel_fn_name(Name, FnName),
    format(S, '; LLVM IR generated by prolog_to_llvm.pl~n', []),
    format(S, '; Kernel: ~w~n', [Name]),
    format(S, '; Mode: BPD substrate, bit-identical emission~n~n', []),
    format(S, 'target triple = "~w"~n~n', [Triple]),
    % Function signature: void @bpd_add_llvm(float* %a, float* %b, float* %x, i32 %n)
    (NInputs =:= 2 ->
        format(S, 'define void @~w(float* noalias %a, float* noalias %b, float* noalias %x, i32 %n) {~n', [FnName])
    ;
        format(S, 'define void @~w(float* noalias %a, float* noalias %x, i32 %n) {~n', [FnName])
    ).

kernel_fn_name(k_add, "bpd_add_llvm").
kernel_fn_name(k_mul, "bpd_mul_llvm").
kernel_fn_name(k_sub, "bpd_sub_llvm").
kernel_fn_name(k_relu, "bpd_relu_llvm").
kernel_fn_name(k_neg, "bpd_neg_llvm").
kernel_fn_name(k_abs, "bpd_abs_llvm").

%% Scalar loop body for binary elementwise ops (add, mul, sub)
emit_scalar_body(S, Name) :-
    kernel_op(Name, elementwise, [_, _], _),
    elementwise_llvm_op(Name, LLVMOp), !,
    format(S, 'entry:~n', []),
    format(S, '  br label %loop.header~n~n', []),
    format(S, 'loop.header:~n', []),
    format(S, '  %i = phi i32 [ 0, %entry ], [ %i.next, %loop.body ]~n', []),
    format(S, '  %cmp = icmp slt i32 %i, %n~n', []),
    format(S, '  br i1 %cmp, label %loop.body, label %exit~n~n', []),
    format(S, 'loop.body:~n', []),
    format(S, '  %idx = sext i32 %i to i64~n', []),
    format(S, '  %a.ptr = getelementptr float, float* %a, i64 %idx~n', []),
    format(S, '  %b.ptr = getelementptr float, float* %b, i64 %idx~n', []),
    format(S, '  %x.ptr = getelementptr float, float* %x, i64 %idx~n', []),
    format(S, '  %a.val = load float, float* %a.ptr, align 4~n', []),
    format(S, '  %b.val = load float, float* %b.ptr, align 4~n', []),
    format(S, '  %result = ~w float %a.val, %b.val~n', [LLVMOp]),
    format(S, '  store float %result, float* %x.ptr, align 4~n', []),
    format(S, '  %i.next = add i32 %i, 1~n', []),
    format(S, '  br label %loop.header~n~n', []).

%% Scalar body for relu: x = max(a, 0)
emit_scalar_body(S, k_relu) :- !,
    format(S, 'entry:~n', []),
    format(S, '  br label %loop.header~n~n', []),
    format(S, 'loop.header:~n', []),
    format(S, '  %i = phi i32 [ 0, %entry ], [ %i.next, %loop.body ]~n', []),
    format(S, '  %cmp = icmp slt i32 %i, %n~n', []),
    format(S, '  br i1 %cmp, label %loop.body, label %exit~n~n', []),
    format(S, 'loop.body:~n', []),
    format(S, '  %idx = sext i32 %i to i64~n', []),
    format(S, '  %a.ptr = getelementptr float, float* %a, i64 %idx~n', []),
    format(S, '  %x.ptr = getelementptr float, float* %x, i64 %idx~n', []),
    format(S, '  %a.val = load float, float* %a.ptr, align 4~n', []),
    format(S, '  %zero = fadd float 0.0, 0.0~n', []),
    format(S, '  %is.pos = fcmp ogt float %a.val, %zero~n', []),
    format(S, '  %result = select i1 %is.pos, float %a.val, float 0.0~n', []),
    format(S, '  store float %result, float* %x.ptr, align 4~n', []),
    format(S, '  %i.next = add i32 %i, 1~n', []),
    format(S, '  br label %loop.header~n~n', []).

%% Scalar body for neg: x = -a
emit_scalar_body(S, k_neg) :- !,
    format(S, 'entry:~n', []),
    format(S, '  br label %loop.header~n~n', []),
    format(S, 'loop.header:~n', []),
    format(S, '  %i = phi i32 [ 0, %entry ], [ %i.next, %loop.body ]~n', []),
    format(S, '  %cmp = icmp slt i32 %i, %n~n', []),
    format(S, '  br i1 %cmp, label %loop.body, label %exit~n~n', []),
    format(S, 'loop.body:~n', []),
    format(S, '  %idx = sext i32 %i to i64~n', []),
    format(S, '  %a.ptr = getelementptr float, float* %a, i64 %idx~n', []),
    format(S, '  %x.ptr = getelementptr float, float* %x, i64 %idx~n', []),
    format(S, '  %a.val = load float, float* %a.ptr, align 4~n', []),
    format(S, '  %result = fneg float %a.val~n', []),
    format(S, '  store float %result, float* %x.ptr, align 4~n', []),
    format(S, '  %i.next = add i32 %i, 1~n', []),
    format(S, '  br label %loop.header~n~n', []).

%% Vectorized body for binary elementwise ops
emit_vectorized_body(S, Name) :-
    kernel_op(Name, elementwise, [_, _], _),
    elementwise_llvm_op(Name, LLVMOp), !,
    get_target(vector_width, VW),
    get_target(alignment, Align),
    format(S, 'entry:~n', []),
    format(S, '  %n.vec = sdiv i32 %n, ~d~n', [VW]),
    format(S, '  %n.tail = srem i32 %n, ~d~n', [VW]),
    format(S, '  br label %vec.header~n~n', []),
    % Vectorized loop
    format(S, 'vec.header:~n', []),
    format(S, '  %vi = phi i32 [ 0, %entry ], [ %vi.next, %vec.body ]~n', []),
    format(S, '  %vcmp = icmp slt i32 %vi, %n.vec~n', []),
    format(S, '  br i1 %vcmp, label %vec.body, label %tail.header~n~n', []),
    format(S, 'vec.body:~n', []),
    format(S, '  %voff = mul i32 %vi, ~d~n', [VW]),
    format(S, '  %vidx = sext i32 %voff to i64~n', []),
    format(S, '  %va.ptr = getelementptr float, float* %a, i64 %vidx~n', []),
    format(S, '  %vb.ptr = getelementptr float, float* %b, i64 %vidx~n', []),
    format(S, '  %vx.ptr = getelementptr float, float* %x, i64 %vidx~n', []),
    format(S, '  %va.vptr = bitcast float* %va.ptr to <~d x float>*~n', [VW]),
    format(S, '  %vb.vptr = bitcast float* %vb.ptr to <~d x float>*~n', [VW]),
    format(S, '  %vx.vptr = bitcast float* %vx.ptr to <~d x float>*~n', [VW]),
    format(S, '  %va.val = load <~d x float>, <~d x float>* %va.vptr, align ~d~n', [VW, VW, Align]),
    format(S, '  %vb.val = load <~d x float>, <~d x float>* %vb.vptr, align ~d~n', [VW, VW, Align]),
    format(S, '  %vresult = ~w <~d x float> %va.val, %vb.val~n', [LLVMOp, VW]),
    format(S, '  store <~d x float> %vresult, <~d x float>* %vx.vptr, align ~d~n', [VW, VW, Align]),
    format(S, '  %vi.next = add i32 %vi, 1~n', []),
    format(S, '  br label %vec.header~n~n', []),
    % Scalar tail
    format(S, 'tail.header:~n', []),
    format(S, '  %ti.start = mul i32 %n.vec, ~d~n', [VW]),
    format(S, '  br label %tail.check~n~n', []),
    format(S, 'tail.check:~n', []),
    format(S, '  %ti = phi i32 [ %ti.start, %tail.header ], [ %ti.next, %tail.body ]~n', []),
    format(S, '  %tcmp = icmp slt i32 %ti, %n~n', []),
    format(S, '  br i1 %tcmp, label %tail.body, label %exit~n~n', []),
    format(S, 'tail.body:~n', []),
    format(S, '  %tidx = sext i32 %ti to i64~n', []),
    format(S, '  %ta.ptr = getelementptr float, float* %a, i64 %tidx~n', []),
    format(S, '  %tb.ptr = getelementptr float, float* %b, i64 %tidx~n', []),
    format(S, '  %tx.ptr = getelementptr float, float* %x, i64 %tidx~n', []),
    format(S, '  %ta.val = load float, float* %ta.ptr, align 4~n', []),
    format(S, '  %tb.val = load float, float* %tb.ptr, align 4~n', []),
    format(S, '  %tresult = ~w float %ta.val, %tb.val~n', [LLVMOp]),
    format(S, '  store float %tresult, float* %tx.ptr, align 4~n', []),
    format(S, '  %ti.next = add i32 %ti, 1~n', []),
    format(S, '  br label %tail.check~n~n', []).

%% Footer: exit block
emit_footer(S) :-
    format(S, 'exit:~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).

%% ═══════════════════════════════════════════════════════════════════════════
%% q8_0 × q8_0 block dot — AVX path (Ivy Bridge: mul+add, NO fma)
%% Landscape coordinate: target=avx (no avx2/fma), the ACTUAL ggml path on this CPU.
%% Per block: int32 dot of 32 int8 pairs (EXACT integer) -> sitofp -> scale by
%% (wd[b]*ad[b]) via fmul -> accumulate via fadd (separate mul+add = the AVX path,
%% _mm256_add_ps(_mm256_mul_ps(deltas,p),accum), NOT _mm256_fmadd_ps).
%% Signature: float @bpd_q8_0_dot(i8* %wq, float* %wd, i8* %aq, float* %ad, i32 %nb)
%%   %wq,%aq: int8 quants laid out [nb][32]. %wd,%ad: per-block fp32 scales (=fp16(d) value).
%% ═══════════════════════════════════════════════════════════════════════════

emit_q8_0_dot(OutputFile) :- emit_q8_0_dot(OutputFile, avx).

emit_q8_0_dot(OutputFile, PathTag) :-
    get_target(triple, Triple),
    open(OutputFile, write, S),
    format(S, '; LLVM IR generated by prolog_to_llvm.pl (BPD substrate)~n', []),
    format(S, '; Kernel: q8_0_dot  path=~w  (Ivy Bridge: mul+add, no fma)~n', [PathTag]),
    format(S, 'target triple = "~w"~n~n', [Triple]),
    format(S, 'define float @bpd_q8_0_dot(i8* noalias %wq, float* noalias %wd, i8* noalias %aq, float* noalias %ad, i32 %nb) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  br label %blk.header~n~n', []),
    format(S, 'blk.header:~n', []),
    format(S, '  %b = phi i32 [ 0, %entry ], [ %b.next, %blk.latch ]~n', []),
    format(S, '  %acc = phi float [ 0.000000e+00, %entry ], [ %acc.next, %blk.latch ]~n', []),
    format(S, '  %bcmp = icmp slt i32 %b, %nb~n', []),
    format(S, '  br i1 %bcmp, label %blk.body, label %exit~n~n', []),
    format(S, 'blk.body:~n', []),
    format(S, '  %boff = mul i32 %b, 32~n', []),
    %% inner int32 dot over 32 lanes (exact integer accumulate)
    format(S, '  br label %dot.header~n~n', []),
    format(S, 'dot.header:~n', []),
    format(S, '  %j = phi i32 [ 0, %blk.body ], [ %j.next, %dot.body ]~n', []),
    format(S, '  %isum = phi i32 [ 0, %blk.body ], [ %isum.next, %dot.body ]~n', []),
    format(S, '  %jcmp = icmp slt i32 %j, 32~n', []),
    format(S, '  br i1 %jcmp, label %dot.body, label %dot.done~n~n', []),
    format(S, 'dot.body:~n', []),
    format(S, '  %lane = add i32 %boff, %j~n', []),
    format(S, '  %lidx = sext i32 %lane to i64~n', []),
    format(S, '  %wq.p = getelementptr i8, i8* %wq, i64 %lidx~n', []),
    format(S, '  %aq.p = getelementptr i8, i8* %aq, i64 %lidx~n', []),
    format(S, '  %wq.b = load i8, i8* %wq.p, align 1~n', []),
    format(S, '  %aq.b = load i8, i8* %aq.p, align 1~n', []),
    format(S, '  %wq.i = sext i8 %wq.b to i32~n', []),
    format(S, '  %aq.i = sext i8 %aq.b to i32~n', []),
    format(S, '  %prod.i = mul i32 %wq.i, %aq.i~n', []),
    format(S, '  %isum.next = add i32 %isum, %prod.i~n', []),
    format(S, '  %j.next = add i32 %j, 1~n', []),
    format(S, '  br label %dot.header~n~n', []),
    format(S, 'dot.done:~n', []),
    %% per-block: scale = wd[b]*ad[b]; prod = scale * sitofp(isum); acc += prod  (mul then add, NOT fma)
    format(S, '  %bidx = sext i32 %b to i64~n', []),
    format(S, '  %wd.p = getelementptr float, float* %wd, i64 %bidx~n', []),
    format(S, '  %ad.p = getelementptr float, float* %ad, i64 %bidx~n', []),
    format(S, '  %wd.v = load float, float* %wd.p, align 4~n', []),
    format(S, '  %ad.v = load float, float* %ad.p, align 4~n', []),
    format(S, '  %scale = fmul float %wd.v, %ad.v~n', []),
    format(S, '  %dotf = sitofp i32 %isum to float~n', []),
    format(S, '  %prod = fmul float %scale, %dotf~n', []),
    format(S, '  %acc.next = fadd float %acc, %prod~n', []),
    format(S, '  br label %blk.latch~n~n', []),
    format(S, 'blk.latch:~n', []),
    format(S, '  %b.next = add i32 %b, 1~n', []),
    format(S, '  br label %blk.header~n~n', []),
    format(S, 'exit:~n', []),
    format(S, '  ret float %acc~n', []),
    format(S, '}~n', []),
    close(S),
    format("Emitted q8_0_dot (path=~w) to ~w~n", [PathTag, OutputFile]).

%% ═══════════════════════════════════════════════════════════════════════════
%% q8_0 dot — AVX VECTOR path: <8 x float> accumulator, matching ggml's compiled
%% vinsertf128/vcvtdq2ps/vmulps/vaddps + hsum_float_8 tree (extracted from objdump).
%% Two blocks/iter: block ib -> lanes 0-3, ib+1 -> lanes 4-7. Integer lane-sums are
%% scalar-exact (4 contiguous products each); fp scale+accumulate is 8-lane vector.
%% This emits the EXACT fp op grouping ggml uses on Ivy Bridge -> target 0 ULP.
%% ═══════════════════════════════════════════════════════════════════════════
emit_q8_0_dot_vec(OutputFile) :-
    get_target(triple, Triple),
    open(OutputFile, write, S),
    format(S, '; q8_0_dot AVX-VECTOR (8-lane fp accumulate + hsum tree, matches ggml compiled)~n', []),
    format(S, 'target triple = "~w"~n~n', [Triple]),
    format(S, 'define float @bpd_q8_0_dot(i8* noalias %wq, float* noalias %wd, i8* noalias %aq, float* noalias %ad, i32 %nb) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  br label %blk.header~n~n', []),
    format(S, 'blk.header:~n', []),
    format(S, '  %b = phi i32 [ 0, %entry ], [ %b.next, %blk.latch ]~n', []),
    format(S, '  %accv = phi <8 x float> [ zeroinitializer, %entry ], [ %accv.next, %blk.latch ]~n', []),
    format(S, '  %b1 = add i32 %b, 1~n', []),
    format(S, '  %bcmp = icmp slt i32 %b1, %nb~n', []),     % while ib+1 < nb (two-block)
    format(S, '  br i1 %bcmp, label %blk.body, label %tail~n~n', []),
    format(S, 'blk.body:~n', []),
    %% lane sums: 8 i32 (lanes 0-3 = block b, lanes 4-7 = block b+1), each = 4 contiguous products
    %% (computed by a fully-unrolled inner accumulation per lane; integer = exact)
    emit_lanesum_unrolled(S),
    %% sitofp <8 x i32> -> <8 x float>
    format(S, '  %pf = sitofp <8 x i32> %lanes to <8 x float>~n', []),
    %% deltas: scale_b in lanes 0-3, scale_{b+1} in lanes 4-7
    format(S, '  %bi = sext i32 %b to i64~n', []),
    format(S, '  %b1i = sext i32 %b1 to i64~n', []),
    format(S, '  %wd0p = getelementptr float, float* %wd, i64 %bi~n', []),
    format(S, '  %ad0p = getelementptr float, float* %ad, i64 %bi~n', []),
    format(S, '  %wd1p = getelementptr float, float* %wd, i64 %b1i~n', []),
    format(S, '  %ad1p = getelementptr float, float* %ad, i64 %b1i~n', []),
    format(S, '  %wd0 = load float, float* %wd0p, align 4~n', []),
    format(S, '  %ad0 = load float, float* %ad0p, align 4~n', []),
    format(S, '  %wd1 = load float, float* %wd1p, align 4~n', []),
    format(S, '  %ad1 = load float, float* %ad1p, align 4~n', []),
    format(S, '  %s0 = fmul float %wd0, %ad0~n', []),
    format(S, '  %s1 = fmul float %wd1, %ad1~n', []),
    %% build deltas vector [s0,s0,s0,s0,s1,s1,s1,s1]
    format(S, '  %d0 = insertelement <8 x float> undef, float %s0, i32 0~n', []),
    format(S, '  %d1 = insertelement <8 x float> %d0, float %s0, i32 1~n', []),
    format(S, '  %d2 = insertelement <8 x float> %d1, float %s0, i32 2~n', []),
    format(S, '  %d3 = insertelement <8 x float> %d2, float %s0, i32 3~n', []),
    format(S, '  %d4 = insertelement <8 x float> %d3, float %s1, i32 4~n', []),
    format(S, '  %d5 = insertelement <8 x float> %d4, float %s1, i32 5~n', []),
    format(S, '  %d6 = insertelement <8 x float> %d5, float %s1, i32 6~n', []),
    format(S, '  %deltas = insertelement <8 x float> %d6, float %s1, i32 7~n', []),
    %% vmulps then vaddps (the AVX path: mul then add, NOT fma)
    format(S, '  %prodv = fmul <8 x float> %deltas, %pf~n', []),
    format(S, '  %accv.next = fadd <8 x float> %accv, %prodv~n', []),
    format(S, '  br label %blk.latch~n~n', []),
    format(S, 'blk.latch:~n', []),
    format(S, '  %b.next = add i32 %b, 2~n', []),
    format(S, '  br label %blk.header~n~n', []),
    %% hsum_float_8: res = accv[0:4] + accv[4:8]; res0+=res2; res1+=res3; ret res0+res1
    format(S, 'tail:~n', []),
    format(S, '  %lo = shufflevector <8 x float> %accv, <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>~n', []),
    format(S, '  %hi = shufflevector <8 x float> %accv, <8 x float> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>~n', []),
    format(S, '  %res4 = fadd <4 x float> %lo, %hi~n', []),
    format(S, '  %movehl = shufflevector <4 x float> %res4, <4 x float> undef, <4 x i32> <i32 2, i32 3, i32 2, i32 3>~n', []),
    format(S, '  %res2 = fadd <4 x float> %res4, %movehl~n', []),
    format(S, '  %r0 = extractelement <4 x float> %res2, i32 0~n', []),
    format(S, '  %r1 = extractelement <4 x float> %res2, i32 1~n', []),
    format(S, '  %sum = fadd float %r0, %r1~n', []),
    format(S, '  ret float %sum~n', []),
    format(S, '}~n', []),
    close(S),
    format("Emitted q8_0_dot AVX-VECTOR to ~w~n", [OutputFile]).

%% emit the 8 integer lane-sums into %lanes (<8 x i32>): lane L (0-3)=block b products [4L..4L+3],
%% lane L (4-7)=block b+1 products [4(L-4)..]. Fully unrolled, scalar i32 loads (exact).
emit_lanesum_unrolled(S) :-
    format(S, '  %boff = mul i32 %b, 32~n', []),
    format(S, '  %b1off = mul i32 %b1, 32~n', []),
    forall(between(0,7,L), emit_one_lane(S, L)),
    %% assemble <8 x i32>
    format(S, '  %L0v = insertelement <8 x i32> undef, i32 %lane0, i32 0~n', []),
    forall(between(1,7,L), (P is L-1, format(S, '  %L~wv = insertelement <8 x i32> %L~wv, i32 %lane~w, i32 ~w~n', [L,P,L,L]))),
    format(S, '  %lanes = add <8 x i32> %L7v, zeroinitializer~n', []).  % %lanes = the assembled vector

% lane L sums 4 contiguous products starting at (base_block_offset + K*4), K = L mod 4.
emit_one_lane(S, L) :-
    ( L < 4 -> Base = '%boff', K = L ; Base = '%b1off', K is L-4 ),
    Start is K*8,
    format(S, '  ; lane ~w (8 products from offset ~w+~w)~n', [L, Base, Start]),
    forall(between(0,7,J), (
        Off is Start+J,
        format(S, '  %l~w_o~w = add i32 ~w, ~w~n', [L,J,Base,Off]),
        format(S, '  %l~w_i~w = sext i32 %l~w_o~w to i64~n', [L,J,L,J]),
        format(S, '  %l~w_wp~w = getelementptr i8, i8* %wq, i64 %l~w_i~w~n', [L,J,L,J]),
        format(S, '  %l~w_ap~w = getelementptr i8, i8* %aq, i64 %l~w_i~w~n', [L,J,L,J]),
        format(S, '  %l~w_wb~w = load i8, i8* %l~w_wp~w, align 1~n', [L,J,L,J]),
        format(S, '  %l~w_ab~w = load i8, i8* %l~w_ap~w, align 1~n', [L,J,L,J]),
        format(S, '  %l~w_we~w = sext i8 %l~w_wb~w to i32~n', [L,J,L,J]),
        format(S, '  %l~w_ae~w = sext i8 %l~w_ab~w to i32~n', [L,J,L,J]),
        format(S, '  %l~w_p~w = mul i32 %l~w_we~w, %l~w_ae~w~n', [L,J,L,J,L,J])
    )),
    format(S, '  %l~w_s0 = add i32 %l~w_p0, %l~w_p1~n', [L,L,L]),
    format(S, '  %l~w_s1 = add i32 %l~w_p2, %l~w_p3~n', [L,L,L]),
    format(S, '  %l~w_s2 = add i32 %l~w_p4, %l~w_p5~n', [L,L,L]),
    format(S, '  %l~w_s3 = add i32 %l~w_p6, %l~w_p7~n', [L,L,L]),
    format(S, '  %l~w_s01 = add i32 %l~w_s0, %l~w_s1~n', [L,L,L]),
    format(S, '  %l~w_s23 = add i32 %l~w_s2, %l~w_s3~n', [L,L,L]),
    format(S, '  %lane~w = add i32 %l~w_s01, %l~w_s23~n', [L,L,L]).

%% ═══════════════════════════════════════════════════════════════════════════
%% q8_0 dot — INTRINSIC path: emits ggml's EXACT instruction sequence via LLVM
%% x86 intrinsics, so the compiled kernel matches ggml instruction-for-instruction
%% (vpsignb/vpmaddubsw/vpmaddwd/vcvtdq2ps/vmulps/vaddps + hsum). -> target 0 ULP.
%% Replicates mul_add_epi8_sse + mul_sum_i8_quad_float (two-block, four 128-halves).
%% ═══════════════════════════════════════════════════════════════════════════
emit_q8_0_dot_intrin(OutputFile) :-
    get_target(triple, Triple),
    open(OutputFile, write, S),
    format(S, '; q8_0_dot INTRINSIC (matches ggml AVX instruction-for-instruction)~n', []),
    format(S, 'target triple = "~w"~n~n', [Triple]),
    %% intrinsic declarations
    format(S, 'declare <16 x i8> @llvm.x86.ssse3.psign.b.128(<16 x i8>, <16 x i8>)~n', []),
    format(S, 'declare <8 x i16> @llvm.x86.ssse3.pmadd.ub.sw.128(<16 x i8>, <16 x i8>)~n', []),
    format(S, 'declare <4 x i32> @llvm.x86.sse2.pmadd.wd(<8 x i16>, <8 x i16>)~n~n', []),
    format(S, 'define float @bpd_q8_0_dot(i8* noalias %wq, float* noalias %wd, i8* noalias %aq, float* noalias %ad, i32 %nb) {~n', []),
    format(S, 'entry:~n  br label %hdr~n~n', []),
    format(S, 'hdr:~n', []),
    format(S, '  %b = phi i32 [ 0, %entry ], [ %bn, %lat ]~n', []),
    format(S, '  %acc = phi <8 x float> [ zeroinitializer, %entry ], [ %accn, %lat ]~n', []),
    format(S, '  %b1 = add i32 %b, 1~n', []),
    format(S, '  %c = icmp slt i32 %b1, %nb~n', []),
    format(S, '  br i1 %c, label %body, label %tail~n~n', []),
    format(S, 'body:~n', []),
    %% --- block b (lanes 0-3) and block b1 (lanes 4-7), each: two <16 x i8> halves ---
    emit_block_lanes(S, 'b', 'p_lo'),     % block b -> <4 x i32> %p_lo
    emit_block_lanes(S, 'b1', 'p_hi'),    % block b1 -> <4 x i32> %p_hi
    %% combine into <8 x i32> (p_lo in lanes 0-3, p_hi in 4-7) = MM256_SET_M128I(p_hi,p_lo)
    format(S, '  %pv32 = shufflevector <4 x i32> %p_lo, <4 x i32> %p_hi, <8 x i32> <i32 0,i32 1,i32 2,i32 3,i32 4,i32 5,i32 6,i32 7>~n', []),
    format(S, '  %pf = sitofp <8 x i32> %pv32 to <8 x float>~n', []),   % vcvtdq2ps
    %% deltas: scale_b in 0-3, scale_b1 in 4-7
    format(S, '  %bi = sext i32 %b to i64~n  %b1i = sext i32 %b1 to i64~n', []),
    emit_scale(S, 'b', '0'),
    emit_scale(S, 'b1', '1'),
    format(S, '  %d0 = insertelement <8 x float> undef, float %sc0, i32 0~n', []),
    format(S, '  %d1 = insertelement <8 x float> %d0, float %sc0, i32 1~n', []),
    format(S, '  %d2 = insertelement <8 x float> %d1, float %sc0, i32 2~n', []),
    format(S, '  %d3 = insertelement <8 x float> %d2, float %sc0, i32 3~n', []),
    format(S, '  %d4 = insertelement <8 x float> %d3, float %sc1, i32 4~n', []),
    format(S, '  %d5 = insertelement <8 x float> %d4, float %sc1, i32 5~n', []),
    format(S, '  %d6 = insertelement <8 x float> %d5, float %sc1, i32 6~n', []),
    format(S, '  %deltas = insertelement <8 x float> %d6, float %sc1, i32 7~n', []),
    format(S, '  %prod = fmul <8 x float> %deltas, %pf~n', []),     % vmulps
    format(S, '  %accn = fadd <8 x float> %acc, %prod~n', []),       % vaddps
    format(S, '  br label %lat~n~n', []),
    format(S, 'lat:~n  %bn = add i32 %b, 2~n  br label %hdr~n~n', []),
    %% hsum_float_8: extract hi128 + lo128, add; movehl; movshdup; add_ss
    format(S, 'tail:~n', []),
    format(S, '  %lo = shufflevector <8 x float> %acc, <8 x float> undef, <4 x i32> <i32 0,i32 1,i32 2,i32 3>~n', []),
    format(S, '  %hi = shufflevector <8 x float> %acc, <8 x float> undef, <4 x i32> <i32 4,i32 5,i32 6,i32 7>~n', []),
    format(S, '  %r4 = fadd <4 x float> %lo, %hi~n', []),
    format(S, '  %mhl = shufflevector <4 x float> %r4, <4 x float> undef, <4 x i32> <i32 2,i32 3,i32 2,i32 3>~n', []),
    format(S, '  %r2 = fadd <4 x float> %r4, %mhl~n', []),
    format(S, '  %e0 = extractelement <4 x float> %r2, i32 0~n', []),
    format(S, '  %e1 = extractelement <4 x float> %r2, i32 1~n', []),
    format(S, '  %s = fadd float %e0, %e1~n', []),
    format(S, '  ret float %s~n}~n', []),
    close(S),
    format("Emitted q8_0_dot INTRINSIC to ~w~n", [OutputFile]).

%% one block (32 int8 at offset BlkVar*32) -> <4 x i32> named PName, via the mul_add_epi8_sse atom
%% on two <16 x i8> halves + pmaddwd + add. BlkVar in {b, b1}.
emit_block_lanes(S, BlkVar, PName) :-
    format(S, '  ; --- block ~w -> ~w (4 i32 lanes) ---~n', [BlkVar, PName]),
    format(S, '  %~w_off = mul i32 %~w, 32~n', [BlkVar, BlkVar]),
    format(S, '  %~w_o64 = sext i32 %~w_off to i64~n', [BlkVar, BlkVar]),
    %% load two <16 x i8> halves of weight + activation
    forall(member(H-Hoff, ['0'-0, '1'-16]), (
        format(S, '  %~w_wp~w = getelementptr i8, i8* %wq, i64 %~w_o64~n', [BlkVar,H,BlkVar]),
        format(S, '  %~w_wp~wb = getelementptr i8, i8* %~w_wp~w, i64 ~w~n', [BlkVar,H,BlkVar,H,Hoff]),
        format(S, '  %~w_ap~w = getelementptr i8, i8* %aq, i64 %~w_o64~n', [BlkVar,H,BlkVar]),
        format(S, '  %~w_ap~wb = getelementptr i8, i8* %~w_ap~w, i64 ~w~n', [BlkVar,H,BlkVar,H,Hoff]),
        format(S, '  %~w_wv~w = bitcast i8* %~w_wp~wb to <16 x i8>*~n', [BlkVar,H,BlkVar,H]),
        format(S, '  %~w_av~w = bitcast i8* %~w_ap~wb to <16 x i8>*~n', [BlkVar,H,BlkVar,H]),
        format(S, '  %~w_x~w = load <16 x i8>, <16 x i8>* %~w_wv~w, align 1~n', [BlkVar,H,BlkVar,H]),
        format(S, '  %~w_y~w = load <16 x i8>, <16 x i8>* %~w_av~w, align 1~n', [BlkVar,H,BlkVar,H]),
        %% mul_add_epi8_sse: ax=psign(x,x), sy=psign(y,x), maddubs(ax,sy) -> <8 x i16>
        format(S, '  %~w_ax~w = call <16 x i8> @llvm.x86.ssse3.psign.b.128(<16 x i8> %~w_x~w, <16 x i8> %~w_x~w)~n', [BlkVar,H,BlkVar,H,BlkVar,H]),
        format(S, '  %~w_sy~w = call <16 x i8> @llvm.x86.ssse3.psign.b.128(<16 x i8> %~w_y~w, <16 x i8> %~w_x~w)~n', [BlkVar,H,BlkVar,H,BlkVar,H]),
        format(S, '  %~w_p16_~w = call <8 x i16> @llvm.x86.ssse3.pmadd.ub.sw.128(<16 x i8> %~w_ax~w, <16 x i8> %~w_sy~w)~n', [BlkVar,H,BlkVar,H,BlkVar,H]),
        %% pmadd.wd with ones -> <4 x i32>
        format(S, '  %~w_p32_~w = call <4 x i32> @llvm.x86.sse2.pmadd.wd(<8 x i16> %~w_p16_~w, <8 x i16> <i16 1,i16 1,i16 1,i16 1,i16 1,i16 1,i16 1,i16 1>)~n', [BlkVar,H,BlkVar,H])
    )),
    %% add the two halves' <4 x i32>
    format(S, '  %~w = add <4 x i32> %~w_p32_0, %~w_p32_1~n', [PName, BlkVar, BlkVar]).

%% scale_N = fp16(wd[blk]) * fp16(ad[blk]) ; loaded from the fp32 arrays (already fp16-valued)
emit_scale(S, BlkVar, N) :-
    format(S, '  %~w_si = sext i32 %~w to i64~n', [BlkVar, BlkVar]),
    format(S, '  %wdp~w = getelementptr float, float* %wd, i64 %~w_si~n', [N, BlkVar]),
    format(S, '  %adp~w = getelementptr float, float* %ad, i64 %~w_si~n', [N, BlkVar]),
    format(S, '  %wdv~w = load float, float* %wdp~w, align 4~n', [N, N]),
    format(S, '  %adv~w = load float, float* %adp~w, align 4~n', [N, N]),
    format(S, '  %sc~w = fmul float %wdv~w, %adv~w~n', [N, N, N]).
