%% SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
%% Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
%% robust_op_match.o.pl — Table(10100) facts, GENERATED FILE.
%%
%% Auto-generated by bpd/tools/wire_referees_to_dashboard.py from:
%%   - stanford_referee.py (authoritative L1 judge: Stanford gate + robust gate)
%%   - verify_robust_ops_auto.py (Iyun's harness, emits coordinates_pinned/1)
%%
%% Per Heath's direction (2026-05-31): Table(10100) IS the accept/reject
%% visualization. The referee is the closed-form judge. No human in the loop.
%%
%% Tier mapping (status -> tier):
%%   BIT_IDENTICAL + robust pass     -> gold
%%   BIT_IDENTICAL canonical only    -> silver
%%   ROBUST_GAP                      -> silver
%%   SHAPE_DIVERGENT                 -> bronze
%%   DIVERGENT (ULP <= 4)            -> bronze
%%   DIVERGENT (ULP > 4) / MISSING   -> untested
%%
%% DO NOT EDIT BY HAND — re-run the pipeline.

:- module(robust_op_match, [robust_op_match/5]).

robust_op_match(conv_im2col, bpd_matmul, pytorch_mkl, silver, [stanford_status('BIT_IDENTICAL'),detail("512^3:0"),robust_gate(not_run_or_unmarked)]).
robust_op_match(unary_elementwise, bpd_relu, pytorch_mkl, silver, [stanford_status('ROBUST_GAP'),detail("stanford 0-ULP; robust maxULP=2147483648"),canonical_pass(true),robust_gate(failed),disagreement_with(gold,[sizes([256, 1024, 8192]),max_ulp(0),neg_zero_stable(true),nan_prop(true),coordinates_pinned(['signed_zero_branch:>=','form:max_identity_zero'])])]).
robust_op_match(unary_elementwise, bpd_leakyrelu, pytorch_mkl, gold, [stanford_status('BIT_IDENTICAL'),detail("64x1024:0 256x1024:0 +robust"),robust_gate(passed)]).
robust_op_match(unary_elementwise, bpd_sigmoid, pytorch_mkl, gold, [stanford_status('BIT_IDENTICAL'),detail("64x1024:0 256x1024:0 +robust"),robust_gate(passed)]).
robust_op_match(unary_elementwise, bpd_tanh, pytorch_mkl, gold, [stanford_status('BIT_IDENTICAL'),detail("64x1024:0 256x1024:0 +robust"),robust_gate(passed)]).
robust_op_match(unary_elementwise, bpd_swish, pytorch_mkl, untested, [stanford_status('MISSING_KERNEL')]).
robust_op_match(unary_elementwise, bpd_gelu, pytorch_mkl, untested, [stanford_status('DIVERGENT'),detail("64x1024:8 256x1024:9"),max_ulp(9),above_bronze_threshold(true)]).
robust_op_match(unary_elementwise, bpd_selu, pytorch_mkl, silver, [stanford_status('ROBUST_GAP'),detail("stanford 0-ULP; robust maxULP=2147483648"),canonical_pass(true),robust_gate(failed),disagreement_with(gold,[sizes([256, 1024, 8192]),max_ulp(0),neg_zero_stable(true),nan_prop(true),coordinates_pinned(['form:expf_minus_1','signed_zero_branch:<=','constants:(scale*alpha)_fold_first','acc_dtype:f32'])])]).
robust_op_match(unary_elementwise, bpd_hardsigmoid, pytorch_mkl, gold, [stanford_status('BIT_IDENTICAL'),detail("64x1024:0 256x1024:0 +robust"),robust_gate(passed)]).
robust_op_match(unary_elementwise, bpd_softplus, pytorch_mkl, gold, [stanford_status('BIT_IDENTICAL'),detail("64x1024:0 256x1024:0 +robust"),robust_gate(passed)]).
robust_op_match(unary_elementwise, bpd_softsign, pytorch_mkl, gold, [stanford_status('BIT_IDENTICAL'),detail("64x1024:0 256x1024:0 +robust"),robust_gate(passed)]).
robust_op_match(unary_elementwise, bpd_elu, pytorch_mkl, silver, [stanford_status('ROBUST_GAP'),detail("stanford 0-ULP; robust maxULP=2147483648"),canonical_pass(true),robust_gate(failed),disagreement_with(gold,[sizes([256, 1024, 8192]),max_ulp(0),neg_zero_stable(true),nan_prop(true),coordinates_pinned(['form:expf_minus_1','signed_zero_branch:<=','acc_dtype:f32'])])]).

%% 12 facts emitted
