#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
# Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
"""
gen_kb_l2_problems.py — regenerate bpd/tests/kernelbench_l2_problems.pl from the
L2 chain-lifter (the single source of truth).

Supersedes the old hand/gen_kb_problems.py-generated file. The lifter auto-derives
each problem's op-chain from the actual KB forward() source + the model's
submodule types, then maps to ggml ops. This is STRICTLY MORE accurate than the
prior file (which used ggml_mul_mat as a placeholder for ConvTranspose etc.):
here ConvTranspose3d -> ggml_conv_transpose_3d, MaxPool -> ggml_pool_2d, etc.

Format kept DROP-IN compatible:
  - module kernelbench_l2, exports kb_problem/4
  - kb_problem(Number, Split, 'Name', [op(name, ggml_kind, seq), ...])   (op/3!)
  - Split = odd Number -> train, even -> test (the prior file's convention,
    the one thing the lifter didn't otherwise carry).
NB: op/3 (not op/4) — test_kernelbench_l2.pl pattern-matches op(_,K,_), so the
canonical problems file stays op/3 for fusion analysis. The param-carrying form
(chain_to_ggml_ir) is a separate output for codegen.

Author: Iyun, 2026-06-08.
"""
import os, re, sys, importlib.util

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from l2_chain_lift import lift_chain, resolve_modules, _GGML_KIND, _ggml_kind_for

KB = "/tmp/llamatov-data/kernelbench/KernelBench/level2"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "tests", "kernelbench_l2_problems.pl")


def problem_number(fname):
    m = re.match(r"(\d+)_", fname)
    return int(m.group(1)) if m else None


def ggml_ops_for(path, model):
    """op/3 list [op(name, ggml_kind, seq), ...] from the lifted+resolved chain."""
    chain = lift_chain(path)
    resolve_modules(chain, model)
    ops = []
    seq = 0
    for step in chain["steps"]:
        op = step["op"]
        if op == "_save":        # DAG marker, no ggml node
            continue
        if op not in _GGML_KIND and op not in ("conv", "convtranspose", "maxpool", "avgpool"):
            continue
        kind = _ggml_kind_for(step)
        if kind is None or kind == "ggml_unknown":
            continue
        seq += 1
        short = op.replace("bpd_", "")
        ops.append(f"op({short}_{seq}, {kind}, {seq})")
    return ops


def main():
    files = sorted((f for f in os.listdir(KB) if f.endswith(".py")),
                   key=lambda f: problem_number(f) or 0)
    rows = []
    errors = []
    for f in files:
        num = problem_number(f)
        if num is None:
            continue
        split = "train" if num % 2 == 1 else "test"     # odd=train, even=test
        try:
            spec = importlib.util.spec_from_file_location("kb_l2_gen", os.path.join(KB, f))
            mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
            init = mod.get_init_inputs() if hasattr(mod, "get_init_inputs") else []
            model = mod.Model(*init) if init else mod.Model()
            ops = ggml_ops_for(os.path.join(KB, f), model)
            name = f[:-3]
            rows.append((num, split, name, ops))
        except Exception as e:
            errors.append((f, str(e)[:80]))

    rows.sort(key=lambda r: r[0])
    with open(OUT, "w") as out:
        out.write("%% kernelbench_l2_problems.pl — Auto-generated from the L2 chain-lifter.\n")
        out.write("%% 100 problems, odd=TRAIN, even=TEST (for generalization validation).\n")
        out.write("%% Generated by bpd/kernelgen/referee/gen_kb_l2_problems.py — the lifter is\n")
        out.write("%% the SINGLE SOURCE OF TRUTH (auto-derived from KB forward() + submodule types;\n")
        out.write("%% more precise ggml mapping than the prior hand-generated file).\n\n")
        out.write(":- module(kernelbench_l2, [kb_problem/4]).\n\n")
        out.write("%% kb_problem(+Number, +Split, +Name, +Ops)\n")
        out.write("%% Ops is a list of op(name, ggml_kind, sequence_number) terms.\n\n")
        for num, split, name, ops in rows:
            opstr = "[" + ", ".join(ops) + "]"
            out.write(f"kb_problem({num}, {split}, '{name}', {opstr}).\n")

    print(f"Wrote {len(rows)} kb_problem/4 facts to {OUT}")
    if errors:
        print(f"  {len(errors)} errors:")
        for f, e in errors[:10]:
            print(f"    {f}: {e}")


if __name__ == "__main__":
    main()
