#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-RTAAL-1.1
# Copyright (c) 2026 Heath Hunnicutt and the Ruach Tov collective.
"""run_divergence_oracles.py — single CI entry point: build + run all 0-ULP oracles,
emit Prolog div_status_vs facts for Table(10011).

  python3 run_divergence_oracles.py --output /path/to/div_fixtures.o.pl

Builds each archived oracle (bpd/model_coverage/oracles/*.c) against the ggml reference,
runs it against the dump fixtures with the proven operand mappings, parses maxULP, and
writes div_status_vs([mistral, layer(l), <section>, <op>], lifted_llamacpp,
measured(output(ulp(N)), perf(unmeasured))). facts.

ULP=0 => GREEN (bit-exact). The mistral coordinate is used because mistral==llama graph
(graph_aliased), and these op-classes were verified against the llama dumps.

Env (override if paths differ):
  REF   = ggml reference build (default <repo>/reference/llama_cpp_canonical_2026_05_21)
  DUMPS = eval-callback dump dir  (default <repo>/tmp/spec_dump_v2)
"""
import os, re, sys, subprocess, glob

HERE   = os.path.dirname(os.path.abspath(__file__))
ORACLE = os.path.join(HERE, "oracles")
REF    = os.environ.get("REF",   "")
DUMPS  = os.environ.get("DUMPS", "")
CC = ["clang", "-mavx", "-mf16c", "-mno-avx2", "-mno-fma",
      f"-I{REF}/ggml/include", f"-L{REF}/build/bin"]
LIBS = ["-lggml-cpu", "-lggml-base", "-lggml", "-lm"]
ENV = {**os.environ, "LD_LIBRARY_PATH": f"{REF}/build/bin", "OMP_NUM_THREADS": "1"}

def D(glob_pat):
    """resolve a dump by glob (handles the eval-callback naming)."""
    g = glob.glob(os.path.join(DUMPS, glob_pat))
    if not g: raise FileNotFoundError(glob_pat)
    return g[0]

def build(name):
    src = os.path.join(ORACLE, f"{name}.c")
    out = f"/tmp/oracle_{name}"
    r = subprocess.run(CC + [src, "-o", out] + LIBS, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"build {name} failed: {r.stderr[:300]}")
    return out

def run_ulp(binpath, args):
    r = subprocess.run([binpath] + args, capture_output=True, text=True, env=ENV, timeout=120)
    m = re.search(r"maxULP=(\d+)", r.stdout)
    if not m:
        raise RuntimeError(f"no maxULP in output: {r.stdout[:200]} {r.stderr[:200]}")
    return int(m.group(1))

# ── ORACLE PLAN: (coordinate, oracle_name, args-builder) ──
# Each entry runs one oracle and maps it to a div_status_vs coordinate.
# Layer-0 cells; the mistral coordinate (== llama graph, graph_aliased).
def plan():
    return [
        (["mistral", "layer(l)", "attn", "norm"],     "rms_norm",
            lambda: [D("0000_GET_ROWS_inp_embd.bin"), D("0002_RMS_NORM_norm-0.bin"), "1e-5"]),
        (["mistral", "layer(l)", "attn", "rope"],      "rope",
            lambda: [D("0009_RESHAPE_Qcur-0*.bin") if glob.glob(os.path.join(DUMPS,"0009_RESHAPE_Qcur-0*.bin")) else D("0009*.bin"),
                     D("0011_ROPE_Qcur-0.bin"), D("0014*rope_freqs*.bin")]),
        (["mistral", "layer(l)", "attn", "score"],     "softmax",
            lambda: [D("0038_MUL_MAT_node_20.bin"), D("0045_SOFT_MAX_node_21_src1.bin"), D("0041_SOFT_MAX_node_21.bin")]),
        (["mistral", "layer(l)", "attn", "qkt"],       "qkt",
            lambda: [D("0011_ROPE_Qcur-0.bin"), D("0018_ROPE_Kcur-0.bin"), D("0038_MUL_MAT_node_20.bin")]),
        (["mistral", "layer(l)", "attn", "scores_v"],  "scores_v",
            lambda: [D("0027_RESHAPE_Vcur-0__reshaped_.bin"), D("0041_SOFT_MAX_node_21.bin"), D("0044_MUL_MAT_node_22.bin")]),
        (["mistral", "layer(l)", "ffn", "silu"],       "silu",
            lambda: [D("0059_MUL_MAT_ffn_gate-0.bin"), D("0061_SILU_ffn_silu-0.bin")]),
    ]

def fact(coord, ulp):
    coord_str = "[" + ", ".join(coord) + "]"
    return (f"div_status_vs({coord_str}, lifted_llamacpp, "
            f"measured(output(ulp({ulp})), perf(unmeasured))).")

def main():
    out_path = None
    if "--output" in sys.argv:
        out_path = sys.argv[sys.argv.index("--output") + 1]

    facts, summary = [], []
    facts.append("%% AUTO-GENERATED by run_divergence_oracles.py — DO NOT EDIT BY HAND.")
    facts.append("%% Builds + runs the bit-exact oracles vs the ggml reference, emits ULP per coordinate.")
    facts.append("%% mistral coordinate == llama graph (graph_aliased). ulp(0) = bit-exact GREEN.")
    facts.append("")
    for coord, oracle_name, args_fn in plan():
        try:
            binpath = build(oracle_name)
            ulp = run_ulp(binpath, args_fn())
            facts.append(fact(coord, ulp))
            summary.append((coord[-1], ulp, "GREEN" if ulp == 0 else "DIVERGENT"))
        except Exception as e:
            summary.append((coord[-1], "ERR", str(e)[:80]))
            facts.append(f"%% {coord[-1]}: ORACLE ERROR: {str(e)[:120]}")

    text = "\n".join(facts) + "\n"
    if out_path:
        with open(out_path, "w") as f:
            f.write(text)
        print(f"wrote {len([s for s in summary if s[1] != 'ERR'])} facts -> {out_path}")
    else:
        print(text)

    print("\n=== ORACLE SUMMARY ===", file=sys.stderr)
    for op, ulp, status in summary:
        print(f"  {op:12s} ulp={ulp!s:>4}  {status}", file=sys.stderr)
    green = sum(1 for _, u, _ in summary if u == 0)
    print(f"  {green}/{len(summary)} GREEN (bit-exact)", file=sys.stderr)
    sys.exit(0 if green == len(summary) else 1)

if __name__ == "__main__":
    main()
